import { 
  User, 
  Character, 
  Quest, 
  Achievement, 
  RewardItem, 
  HistoryRecord, 
  ProgressSummary 
} from '../types';

export const initialUser: User = {
  id: 'usr_001',
  name: 'Aiden Vance',
  email: 'hero@liferpg.dev',
  avatar: '',
  createdAt: '2026-08-01T08:00:00.000Z',
  preferences: {
    theme: 'fantasy-dark',
    soundEnabled: true,
    reducedMotion: false,
    notifications: true,
  },
};

export const initialCharacter: Character = {
  id: 'char_001',
  userId: 'usr_001',
  name: 'Aiden Vance',
  heroClass: 'Scholar',
  title: 'Grand Arcane Polymath',
  avatarUrl: '',
  level: 12,
  xp: 2450,
  gold: 1240,
  streak: 14,
  longestStreak: 31,
  streakProtectionActive: true,
  streakHistory: [
    { day: 'M', date: '2026-09-05', completed: true },
    { day: 'T', date: '2026-09-06', completed: true },
    { day: 'W', date: '2026-09-07', completed: true },
    { day: 'T', date: '2026-09-08', completed: true },
    { day: 'F', date: '2026-09-09', completed: true },
    { day: 'S', date: '2026-09-10', completed: true },
    { day: 'S', date: '2026-09-11', completed: true },
  ],
  attributes: {
    strength: 42,
    intelligence: 67,
    wisdom: 31,
    discipline: 54,
    endurance: 45,
    creativity: 28,
  },
  equipment: {
    weapon: 'Shadow Blade of Focus',
    armor: 'Rune-Woven Scholar Cloak',
    boots: 'Boots of Prompt Execution',
    ring: 'Ring of Deep Contemplation',
    pet: 'Cyber Gryphon Companion',
  },
  recentGains: {
    intelligence: 12,
    discipline: 8,
    strength: 5,
    creativity: 4,
  },
};

// Helper to generate dynamic deadlines relative to current time so timers always tick and highlight appropriately
export const getRelativeDeadline = (hoursFromNow: number, minutesFromNow = 0) => {
  const d = new Date();
  d.setHours(d.getHours() + hoursFromNow);
  d.setMinutes(d.getMinutes() + minutesFromNow);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  const hours = String(d.getHours()).padStart(2, '0');
  const minutes = String(d.getMinutes()).padStart(2, '0');
  return {
    dueDate: `${year}-${month}-${day}`,
    dueTime: `${hours}:${minutes}`,
  };
};

export const initialQuests: Quest[] = [
  {
    id: 'qst_101',
    userId: 'usr_001',
    title: 'Study DBMS for 2 hours',
    description: 'Master index optimization, B-trees, and transaction isolation levels for the upcoming systems review.',
    category: 'Knowledge',
    difficulty: 'Hard',
    estimatedTime: '2h',
    xpReward: 80,
    goldReward: 25,
    attribute: 'intelligence',
    attributeReward: 8,
    ...getRelativeDeadline(1, 45), // Due in 1h 45m (Urgent: < 4h)
    status: 'Active',
    repeat: 'Daily',
    createdAt: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'qst_102',
    userId: 'usr_001',
    title: 'Practice React & State Architecture',
    description: 'Refactor state machine hooks and implement optimistic UI updates with zero flicker.',
    category: 'Coding',
    difficulty: 'Medium',
    estimatedTime: '1h 30m',
    xpReward: 50,
    goldReward: 20,
    attribute: 'intelligence',
    attributeReward: 5,
    ...getRelativeDeadline(3, 15), // Due in 3h 15m (Urgent: < 4h)
    status: 'Active',
    repeat: 'Daily',
    createdAt: '2026-09-11T09:00:00.000Z',
  },
  {
    id: 'qst_103',
    userId: 'usr_001',
    title: 'Morning Workout & Calisthenics',
    description: '45 minutes HIIT session + weighted pull-ups and core workout for physical resilience.',
    category: 'Fitness',
    difficulty: 'Medium',
    estimatedTime: '45m',
    xpReward: 40,
    goldReward: 15,
    attribute: 'strength',
    attributeReward: 5,
    ...getRelativeDeadline(8, 30), // Due in 8h 30m (Standard active)
    status: 'Active',
    repeat: 'Daily',
    createdAt: '2026-09-11T07:00:00.000Z',
  },
  {
    id: 'qst_104',
    userId: 'usr_001',
    title: 'Read 25 Pages of Philosophy',
    description: 'Marcus Aurelius Meditations, Book IV notes with personal journal reflections.',
    category: 'Knowledge',
    difficulty: 'Easy',
    estimatedTime: '30m',
    xpReward: 35,
    goldReward: 12,
    attribute: 'wisdom',
    attributeReward: 4,
    ...getRelativeDeadline(18, 0), // Due tomorrow
    status: 'Active',
    repeat: 'Daily',
    createdAt: '2026-09-11T08:30:00.000Z',
  },
  {
    id: 'qst_105',
    userId: 'usr_001',
    title: 'Ship Hackathon Core Engine Demo',
    description: 'Assemble all micro-services, connect visual sound triggers and run responsive layout audits.',
    category: 'Coding',
    difficulty: 'Epic',
    estimatedTime: '3h',
    xpReward: 180,
    goldReward: 90,
    attribute: 'creativity',
    attributeReward: 18,
    dueDate: '2026-09-13',
    status: 'Active',
    repeat: 'None',
    createdAt: '2026-09-10T14:00:00.000Z',
  },
  {
    id: 'qst_106',
    userId: 'usr_001',
    title: '20-Minute Deep Mindful Meditation',
    description: 'Box breathing exercises without device distractions to clear cognitive fatigue.',
    category: 'Health',
    difficulty: 'Easy',
    estimatedTime: '20m',
    xpReward: 30,
    goldReward: 10,
    attribute: 'discipline',
    attributeReward: 3,
    dueDate: '2026-09-11',
    status: 'Completed',
    repeat: 'Daily',
    createdAt: '2026-09-11T06:00:00.000Z',
    completedAt: '2026-09-11T06:25:00.000Z',
  },
  {
    id: 'qst_107',
    userId: 'usr_001',
    title: 'Hydration Challenge: 3L Water',
    description: 'Maintain cellular hydration throughout intense programming sessions.',
    category: 'Health',
    difficulty: 'Easy',
    estimatedTime: 'All day',
    xpReward: 25,
    goldReward: 10,
    attribute: 'endurance',
    attributeReward: 3,
    dueDate: '2026-09-11',
    status: 'Completed',
    repeat: 'Daily',
    createdAt: '2026-09-11T08:00:00.000Z',
    completedAt: '2026-09-11T19:15:00.000Z',
  },
];

export const recommendedQuests = [
  {
    title: 'Study for 1 hour',
    description: 'Deep focused study block without phone or notifications.',
    category: 'Knowledge' as const,
    difficulty: 'Medium' as const,
    estimatedTime: '1h',
    xpReward: 40,
    goldReward: 15,
    attribute: 'intelligence' as const,
    attributeReward: 4,
  },
  {
    title: 'Run 3 KM',
    description: 'Paced outdoor or treadmill cardio to elevate VO2 max and energy.',
    category: 'Fitness' as const,
    difficulty: 'Medium' as const,
    estimatedTime: '30m',
    xpReward: 50,
    goldReward: 20,
    attribute: 'endurance' as const,
    attributeReward: 5,
  },
  {
    title: 'Read 20 pages',
    description: 'Expand your perspective with high-signal non-fiction or literature.',
    category: 'Knowledge' as const,
    difficulty: 'Easy' as const,
    estimatedTime: '30m',
    xpReward: 25,
    goldReward: 10,
    attribute: 'wisdom' as const,
    attributeReward: 2,
  },
  {
    title: 'Code for 1 hour',
    description: 'Work on personal projects, algorithms, or open-source repositories.',
    category: 'Coding' as const,
    difficulty: 'Medium' as const,
    estimatedTime: '1h',
    xpReward: 45,
    goldReward: 18,
    attribute: 'intelligence' as const,
    attributeReward: 5,
  },
  {
    title: 'Meditate for 10 minutes',
    description: 'Ground your awareness, lower cortisol, and sharpen executive function.',
    category: 'Health' as const,
    difficulty: 'Easy' as const,
    estimatedTime: '10m',
    xpReward: 20,
    goldReward: 10,
    attribute: 'discipline' as const,
    attributeReward: 2,
  },
  {
    title: 'Drink 2.5L Water Daily',
    description: 'Track daily water intake for optimum focus and energy vitality.',
    category: 'Health' as const,
    difficulty: 'Easy' as const,
    estimatedTime: 'All day',
    xpReward: 25,
    goldReward: 10,
    attribute: 'endurance' as const,
    attributeReward: 3,
  },
  {
    title: 'Sketch or Compose Creative Idea',
    description: 'Spend 45 minutes on unconstrained digital art, design wireframes, or music.',
    category: 'Creativity' as const,
    difficulty: 'Medium' as const,
    estimatedTime: '45m',
    xpReward: 45,
    goldReward: 20,
    attribute: 'creativity' as const,
    attributeReward: 5,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach_001',
    name: 'FIRST QUEST',
    description: 'Complete your first quest in the real world.',
    iconName: 'Award',
    category: 'Quests',
    requirement: 'Complete 1 quest',
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedAt: '2026-08-02T12:00:00.000Z',
    rewardXp: 50,
    rewardGold: 50,
  },
  {
    id: 'ach_002',
    name: 'ON FIRE',
    description: 'Maintain an unbroken 7-day quest streak.',
    iconName: 'Flame',
    category: 'Streak',
    requirement: '7-day streak',
    progress: 7,
    maxProgress: 7,
    unlocked: true,
    unlockedAt: '2026-08-08T18:30:00.000Z',
    rewardXp: 150,
    rewardGold: 100,
  },
  {
    id: 'ach_003',
    name: 'SCHOLAR',
    description: 'Reach 50 Intelligence points through persistent study.',
    iconName: 'Brain',
    category: 'Attributes',
    requirement: 'Reach 50 Intelligence',
    progress: 67,
    maxProgress: 50,
    unlocked: true,
    unlockedAt: '2026-08-25T14:10:00.000Z',
    rewardXp: 200,
    rewardGold: 150,
  },
  {
    id: 'ach_004',
    name: 'QUEST MASTER',
    description: 'Complete 100 real-world quests on your journey.',
    iconName: 'Swords',
    category: 'Quests',
    requirement: 'Complete 100 quests',
    progress: 67,
    maxProgress: 100,
    unlocked: false,
    rewardXp: 500,
    rewardGold: 350,
  },
  {
    id: 'ach_005',
    name: 'LEGEND',
    description: 'Ascend to Level 25 and master mortal boundaries.',
    iconName: 'Crown',
    category: 'Level',
    requirement: 'Reach Level 25',
    progress: 12,
    maxProgress: 25,
    unlocked: false,
    rewardXp: 1000,
    rewardGold: 750,
  },
  {
    id: 'ach_006',
    name: 'IRON DISCIPLINE',
    description: 'Sustain a 30-day streak of daily accomplishments.',
    iconName: 'ShieldAlert',
    category: 'Streak',
    requirement: '30-day streak',
    progress: 14,
    maxProgress: 30,
    unlocked: false,
    rewardXp: 400,
    rewardGold: 300,
  },
  {
    id: 'ach_007',
    name: 'TITAN OF ENDURANCE',
    description: 'Raise Endurance attribute to 50.',
    iconName: 'HeartHandshake',
    category: 'Attributes',
    requirement: 'Reach 50 Endurance',
    progress: 45,
    maxProgress: 50,
    unlocked: false,
    rewardXp: 250,
    rewardGold: 150,
  },
];

export const initialRewards: RewardItem[] = [
  {
    id: 'rew_001',
    name: 'Shadow Sword',
    description: 'Forged in obsidian clarity. Yields +10% focus and +5 Strength visual aura.',
    price: 500,
    category: 'Gear',
    icon: 'Sword',
    rarity: 'Epic',
    owned: true,
    equipped: true,
    statBonus: { attribute: 'strength', amount: 5 },
  },
  {
    id: 'rew_002',
    name: 'Cyber Theme',
    description: 'Transforms UI panels with futuristic neon accents and glowing HUD rings.',
    price: 300,
    category: 'Themes',
    icon: 'Palette',
    rarity: 'Rare',
    owned: false,
  },
  {
    id: 'rew_003',
    name: 'Dragon Badge',
    description: 'Exclusive title crest displayed on leaderboard and profile sheet.',
    price: 750,
    category: 'Badges',
    icon: 'ShieldCheck',
    rarity: 'Legendary',
    owned: false,
  },
  {
    id: 'rew_004',
    name: 'Mystic Pet',
    description: 'An ethereal astral familiar that hovers by your avatar and cheers completions.',
    price: 1000,
    category: 'Pets',
    icon: 'Sparkles',
    rarity: 'Legendary',
    owned: false,
  },
  {
    id: 'rew_005',
    name: 'Boots of Haste',
    description: 'Reduces perceived friction when starting tough tasks. +4 Discipline bonus.',
    price: 450,
    category: 'Gear',
    icon: 'Zap',
    rarity: 'Rare',
    owned: false,
    statBonus: { attribute: 'discipline', amount: 4 },
  },
  {
    id: 'rew_006',
    name: 'Solar Flare Theme',
    description: 'Warm gold and solar embers wash across your command decks.',
    price: 350,
    category: 'Themes',
    icon: 'Sun',
    rarity: 'Rare',
    owned: false,
  },
  {
    id: 'rew_007',
    name: 'Ring of Deep Contemplation',
    description: 'Channels mental flow during intense study blocks. +6 Intelligence.',
    price: 600,
    category: 'Gear',
    icon: 'Compass',
    rarity: 'Epic',
    owned: true,
    equipped: true,
    statBonus: { attribute: 'intelligence', amount: 6 },
  },
  {
    id: 'rew_008',
    name: 'Rune-Woven Scholar Cloak',
    description: 'Silken robe with enchanted ink threads. +8 Wisdom aesthetic.',
    price: 850,
    category: 'Gear',
    icon: 'Shield',
    rarity: 'Epic',
    owned: true,
    equipped: true,
  },
];

export const initialHistory: HistoryRecord[] = [
  {
    id: 'his_001',
    questId: 'qst_106',
    title: '20-Minute Deep Mindful Meditation',
    category: 'Health',
    xpGained: 30,
    goldGained: 10,
    attributeGained: { attribute: 'discipline', amount: 3 },
    timestamp: 'Today, 06:25 AM',
    type: 'quest_complete',
  },
  {
    id: 'his_002',
    questId: 'qst_107',
    title: 'Hydration Challenge: 3L Water',
    category: 'Health',
    xpGained: 25,
    goldGained: 10,
    attributeGained: { attribute: 'endurance', amount: 3 },
    timestamp: 'Today, 07:15 PM',
    type: 'quest_complete',
  },
  {
    id: 'his_003',
    title: 'Study DBMS for 2 hours',
    category: 'Knowledge',
    xpGained: 80,
    goldGained: 25,
    attributeGained: { attribute: 'intelligence', amount: 8 },
    timestamp: 'Yesterday, 04:30 PM',
    type: 'quest_complete',
  },
  {
    id: 'his_004',
    title: 'Practice React Component Architectures',
    category: 'Coding',
    xpGained: 50,
    goldGained: 20,
    attributeGained: { attribute: 'intelligence', amount: 5 },
    timestamp: 'Yesterday, 02:15 PM',
    type: 'quest_complete',
  },
  {
    id: 'his_005',
    title: 'Morning 5K Trail Run',
    category: 'Fitness',
    xpGained: 60,
    goldGained: 25,
    attributeGained: { attribute: 'endurance', amount: 6 },
    timestamp: 'Sep 09, 07:00 AM',
    type: 'quest_complete',
  },
  {
    id: 'his_006',
    title: 'Read 30 Pages: Clean Code',
    category: 'Knowledge',
    xpGained: 35,
    goldGained: 15,
    attributeGained: { attribute: 'wisdom', amount: 4 },
    timestamp: 'Sep 08, 09:30 PM',
    type: 'quest_complete',
  },
];

export const mockHistory = initialHistory;

export const initialProgressSummary: ProgressSummary = {
  currentLevel: 12,
  totalXp: 2450,
  totalQuestsCompleted: 67,
  currentStreak: 14,
  longestStreak: 31,
  totalGoldEarned: 3480,
  chartData: [
    { date: 'Sep 05', xp: 180, quests: 4 },
    { date: 'Sep 06', xp: 220, quests: 5 },
    { date: 'Sep 07', xp: 140, quests: 3 },
    { date: 'Sep 08', xp: 260, quests: 6 },
    { date: 'Sep 09', xp: 310, quests: 7 },
    { date: 'Sep 10', xp: 195, quests: 4 },
    { date: 'Sep 11', xp: 245, quests: 5 },
  ],
  timeline: [
    { level: 1, unlockedTitle: 'Apprentice Seeker', date: 'Aug 01, 2026' },
    { level: 3, unlockedTitle: 'Disciplined Journeyman', date: 'Aug 08, 2026' },
    { level: 6, unlockedTitle: 'Focus Adept', date: 'Aug 18, 2026' },
    { level: 9, unlockedTitle: 'Master of Will', date: 'Aug 28, 2026' },
    { level: 12, unlockedTitle: 'Grand Arcane Polymath', date: 'Sep 07, 2026' },
  ],
};
